### ISSUE TITLE
When I try to start a new run with all hints vague, the run does not start

### ISSUE THREAD

**Issue by Johncook2** [GameWyrm/OuterWildsScavengerHunt#6]
I have tested a little bit and the only thing I have intentionally changed is how many hints are vague.

**Comment by GameWyrm** [comment]
Does it work with other hint settings?

**Comment by Johncook2** [comment]
Seems to, works with the starting setting and the mostly vague setting

**Comment by Johncook2** [comment]
Doesn't work with all precise either

**Comment by GameWyrm** [comment]
Alright, I'll check it out when I get home, probably a typo somewhere. Thanks for the heads up.

**Comment by Johncook2** [comment]
It doesn't work for all vague or all precise, but it works for all the others

**Comment by Johncook2** [comment]
Also thanks for making the mod, seems like a great way to randomize Outer wilds!

**Comment by GameWyrm** [comment]
Fixed in 0.9.4
